### ISSUE TITLE
Error when running daliserver

### ISSUE THREAD

**Issue by gabiSRC** [onitake/daliserver#19]
Hello there,
I am currently trying to use daliserver with a tridonic dali - usb adapter.
I am on macOS Sierra and I followed the step to install daliserver and the kext file is in my /System/Library/Extensions/

When I run the daliserver command (as root) I got an error:
```
$ daliserver
DALI USB multiplexer (daliserver)
Copyright (c) 2011 onitake All rights reserved.

[2018-05-06 15:08:06] INFO Starting daliserver
[2018-05-06 15:08:06] **ERROR** Can't find USB device
[2018-05-06 15:08:06] INFO Exiting
```
My tridonic is connected to my USB port but it is not connected to any DALI bus.

I am new with DALI so I still struggle to understand how everything works so I wonder if I need to connect a ballast to my adapter first or if I need to install any driver on my mac

In /dev/tty* I could not find any USB

Thank you for the help :)

**Comment by onitake** [comment]
I'm afraid that I have bad news for you: With recent macOS versions, it's no longer possible to claim certain USB devices with a dummy kext. Apple requires all device-specific kernel extensions to be signed, which in turn requires a special developer contract with Apple (the normal app store developer program is not sufficient). Since this contract is specifically designed with hardware vendors in mind, it's game over for anybody who wants to develop support for third party devices - in particular open source developers.

The only options you have are:
1. Disable kernel extension signature checks, which is generally a bad idea, but works. Just google for "osx load unsigned kext" to find instructions.
2. Run Linux in a virtual machine, pass the USB device to the VM and use the adapter from there.
3. Help write a new usb.c implementation that uses IOHIDManager instead of libusb. Since the Tridonic adapter enumerates as a HID, it can be accessed via macOS's Human Input Device API. This is also the reason why a dummy kext is required in the first place, by the way...

**Comment by gabiSRC** [comment]
Hello,
Oh, ok thank you, I will try the first option in order to validate that all is working as expected.

I will then try to use a docker container to use the dali server but I wonder which interface I should pass to it (or to a VM)? Is it /dev/ttyUSB?

Thank you

**Comment by whatcall** [comment]
okay, even though I get the answer that why I try every step as readme but got error too.

**Comment by whatcall** [comment]
okay, even though I get the answer that why I try every step as readme but got error too.

**Comment by whatcall** [comment]
Thanks, finally I get the answer that why I try every step as readme but got error too.

**Comment by gabiSRC** [comment]
Hello,
Ok it is good for me, using a docker container hosted on a raspi 3, I passed the usb bus to the docker and run in privileged mode, when I execute the daliserver all seems right:
```
$ daliserver
DALI USB multiplexer (daliserver)
Copyright (c) 2011 onitake All rights reserved.

[2018-05-11 08:18:24] INFO Starting daliserver
[2018-05-11 08:18:24] INFO Kernel driver is active, trying to detach
[2018-05-11 08:18:24] INFO Server ready, waiting for events
```
To pass the usb bus in the docker : --device="/dev/bus/usb/:/dev/bus/usb/" --privileged

Thank you for the help
